spring.application.name=Job-Ingestion-Platform
spring.config.import=optional:file:.env[.properties]

#Connection URL
spring.datasource.url=jdbc:postgresql://localhost:5432/{$DATABASE_NAME}
spring.datasource.username={$DATABASE_USERNAME}
spring.datasource.password={$DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


app.scheduler.ingestion-fixed-delay-ms=120000
